/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a tenant-scoped closed-corpus question. */
        post: operations["submitQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a source document for tenant corpus review. */
        post: operations["uploadSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read ingestion job status. */
        get: operations["getIngestJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenant corpus chunks visible to the caller role. */
        get: operations["listCorpus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corpus/{chunkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve, reject, or update review metadata for a chunk. */
        patch: operations["reviewChunk"];
        trace?: never;
    };
    "/tenant/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read safe tenant configuration. */
        get: operations["getTenantConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update safe tenant configuration fields only. */
        patch: operations["updateTenantConfig"];
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a pipeline run trace.
         * @description Returns the run trace if the requesting principal can read it. The principal can read
         *     a trace when `tenant_id == principal.tenantId` AND (`user_id == principal.userId` OR
         *     the principal holds the `admin:queries:read` scope). When the rule fails the endpoint
         *     returns **404** (not 403) to avoid disclosing the existence of run IDs that belong to
         *     other users.
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List query log rows for the tenant. */
        get: operations["listAdminQueries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/flagged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List flagged queries for the tenant. */
        get: operations["listFlaggedQueries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit entries for the tenant. */
        get: operations["listAuditEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/queries/{runId}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a single query's raw (un-redacted) sensitive fields. Admin-only.
         * @description Returns the raw query text and any decrypted sensitive log payload for a single
         *     query, bypassing the default redaction applied by `/admin/queries`. Restricted
         *     to the `admin` role. Each successful read writes an `audit_entries` row with
         *     `action='raw_sensitive_view'` and the requesting principal's `actor_user_id`.
         */
        get: operations["getAdminQueryRaw"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/model-routes/{routeId}/certify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark a model route as certified for production use. Owner role only.
         * @description Sets `model_routes.certification_status='certified'` on the named route. Only
         *     principals with role `owner` may call this endpoint (per ADR 0004). The change
         *     is recorded in `audit_entries` with `action='model_route_certified'`. Routes
         *     cannot be un-certified via this endpoint; deprecation is handled separately.
         */
        patch: operations["certifyModelRoute"];
        trace?: never;
    };
    "/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe webhook intake. */
        post: operations["stripeWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clerk webhook intake. */
        post: operations["clerkWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/make": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make.com webhook intake (deferred – Phase 2).
         * @description URL contract is locked for Phase 2. The handler is not active in Phase 1 and ALL
         *     requests — including those with valid HMAC headers and bodies — return 501 with
         *     error code `feature_deferred`. The header and request-body specification below
         *     documents the Phase 2 activation contract; Phase 1 implementations MUST NOT parse
         *     signatures or bodies. Activation requires founder sign-off and a Make.com
         *     integration spec.
         */
        post: operations["makeWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AnswerMode: "consensus" | "institutional_policy" | "scholarly_dispute" | "pastoral_guidance" | "insufficient";
        /**
         * @description SSE 'data:' payload for POST /query when streamProgress=true. The 'event:'
         *     SSE field disambiguates which variant applies: 'progress' →
         *     ProgressVariant; 'done' → VerifiedResponse; 'error' → ApiError. See
         *     docs/contracts/code-gen-guide.md §Server-Sent Events for the wire
         *     grammar and docs/schemas/progress-event.schema.json for the canonical
         *     JSON Schema.
         */
        ProgressEvent: components["schemas"]["ProgressVariant"] | components["schemas"]["verified-response.schema"] | components["schemas"]["ApiError"];
        /**
         * @description SSE 'event: progress' payload. Emitted zero or more times during a
         *     fresh model run; never emitted on a cache hit.
         */
        ProgressVariant: {
            /**
             * @description Canonical stage identifier. The cache_lookup and cache_store
             *     stages from run-trace.schema.json are deliberately omitted from
             *     this enum so cache hits do not leak hit/miss timing.
             * @enum {string}
             */
            stage: "a1_a2_query_analyzer" | "a3_retrieval" | "a4_evidence_packager" | "a5_composer" | "a6_verifier";
            /**
             * @description Cumulative milliseconds since request receipt, server-measured,
             *     monotonic across events within a single run.
             */
            elapsedMs: number;
            /**
             * @description Optional. Certified ModelRoute.routeId when the stage invoked a
             *     provider (typically a1_a2_query_analyzer, a5_composer, optional
             *     a6_verifier judge). Omitted for deterministic stages.
             */
            modelRouteId?: string | null;
        };
        /** @description Acknowledgement returned by /webhooks/{stripe,clerk}. The receiver durably enqueues the event before returning; the upstream provider may safely treat this as success and stop retrying. */
        WebhookAck: {
            /** @constant */
            received: true;
            /** @description The provider-assigned event id when present in the request payload, echoed back for client-side correlation. May be null if the request body omitted it. */
            eventId?: string | null;
        };
        ApiError: {
            /** @description Stable code from docs/contracts/error-taxonomy.md. */
            code: string;
            message: string;
            traceId: string;
            details?: {
                [key: string]: unknown;
            };
            /** @default false */
            retryable: boolean;
            retryAfterSeconds?: number | null;
        };
        ClassifiedQuery: components["schemas"]["classified-query.schema"];
        RetrievalPlan: components["schemas"]["retrieval-plan.schema"];
        EvidencePacket: components["schemas"]["evidence-packet.schema"];
        VerifiedResponse: components["schemas"]["verified-response.schema"];
        Principal: components["schemas"]["principal.schema"];
        CalendarProfile: components["schemas"]["calendar-profile.schema"];
        Tenant: components["schemas"]["tenant.schema"];
        User: components["schemas"]["user.schema"];
        Source: components["schemas"]["source.schema"];
        Chunk: components["schemas"]["chunk.schema"];
        Session: components["schemas"]["session.schema"];
        IngestJob: components["schemas"]["ingest-job.schema"];
        BillingUsage: components["schemas"]["billing-usage.schema"];
        AuditEntry: components["schemas"]["audit-entry.schema"];
        FlaggedQuery: components["schemas"]["flagged-query.schema"];
        ModelRoute: components["schemas"]["model-route.schema"];
        RunTrace: components["schemas"]["run-trace.schema"];
        /** VerifiedResponse */
        "verified-response.schema": {
            answer: string;
            /** @enum {string} */
            confidenceTier: "GREEN" | "YELLOW" | "RED";
            /** @enum {string} */
            handling: "answer" | "answer_with_disclaimer" | "reframe_to_teaching" | "block_with_redirect" | "insufficient_evidence";
            citations: {
                citationId: string;
                chunkId: string;
                sourceId: string;
                title: string;
                work?: string | null;
                father?: string | null;
                page?: string | null;
                timestamp?: string | null;
                quote?: string | null;
                /** @description Source-level integrity hash carried from EvidencePacket admittedChunks.sourceHash. */
                sourceHash: string;
                /** @description Chunk-level integrity hash carried from EvidencePacket admittedChunks.chunkHash. */
                chunkHash: string;
                /**
                 * @description Always true. A6 admits only approved chunks; this is restated on the user-facing citation for downstream consumers and audit.
                 * @constant
                 */
                approved: true;
                /**
                 * @description Disclosure of the corpus the chunk came from. starter_corpus only appears when the tenant has the (Phase 2) feature enabled.
                 * @enum {string}
                 */
                corpusOrigin: "tenant" | "starter_corpus";
            }[];
            verification: {
                passed: boolean;
                /** Format: date-time */
                checkedAt: string;
                verifierVersion: string;
                failureReason?: string | null;
            };
            reframing: {
                wasReframed: boolean;
                originalQuery?: string | null;
                reframedQuery?: string | null;
                disclosureText?: string | null;
            };
            /** @description Per-request accounting per ADR 0005. servedAnswerCount is always incremented (cache or fresh). freshModelRunCount only on cache miss. */
            usage: {
                servedAnswerCount: number;
                freshModelRunCount: number;
                modelRouteId: string | null;
                promptTokens?: number | null;
                completionTokens?: number | null;
            };
            /** @description ULID identifying the pipeline run. Always present. Even on hard-safety bypass, a runId is minted and a minimal run_traces row is persisted (see phase1-implementation-contract.md §Run-trace persistence is unconditional). */
            runId?: string;
            servedFromCache: boolean;
            /** @description Format YYYY-MM-DD.NN per docs/contracts/api-versioning.md. */
            schemaVersion: string;
            /** @description Present (non-null) only for scholarly_dispute answers (T-006 §Scholarly Dispute UX). Competing positions rendered side-by-side; each position's citationIds are scoped to that column and reference the top-level citations[] — citations are NEVER aggregated across columns. Add-only optional field (api-versioning.md §Add-only changes do not bump), so schemaVersion is unchanged. */
            positions?: {
                /** @description Neutral label for the position, drawn from the evidence (father/work/council/era). Never model-invented. */
                name: string;
                /** @description Short composed statement of this position, verified against this column's chunks only. */
                thesis: string;
                /** @description citationId values from the top-level citations[] belonging to THIS column only. */
                citationIds: string[];
                /**
                 * @description Confidence for this column alone, via the same A4 coverage rule applied to the column's chunks.
                 * @enum {string}
                 */
                confidenceTier: "GREEN" | "YELLOW" | "RED";
            }[] | null;
        } & ({
            /** @enum {unknown} */
            handling?: "answer" | "answer_with_disclaimer" | "reframe_to_teaching";
        } | {
            /** @enum {unknown} */
            handling?: "block_with_redirect" | "insufficient_evidence";
        });
        /**
         * IngestJob
         * @description Async ingestion job tracking upload → extract → chunk → embed → review-queue.
         */
        "ingest-job.schema": {
            jobId: string;
            tenantId: string;
            userId: string;
            sourceId: string;
            /** @enum {string} */
            status: "queued" | "extracting" | "chunking" | "embedding" | "awaiting_review" | "completed" | "failed" | "cancelled";
            progress?: {
                stage?: string;
                completed?: number;
                total?: number;
            };
            errorCode?: string | null;
            errorMessage?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
        };
        /**
         * Chunk
         * @description Indexed retrievable chunk. The Qdrant payload mirrors the same fields plus the embedding vector.
         */
        "chunk.schema": {
            chunkId: string;
            sourceId: string;
            tenantId: string;
            text: string;
            chunkHash: string;
            /** @default false */
            approved: boolean;
            /** @enum {string} */
            visibility: "member" | "scholar" | "admin_only" | "suppressed";
            father?: string | null;
            work?: string | null;
            /** @description Legacy single-page citation string. New chunks emitted under the hierarchical chunking contract populate pageStart/pageEnd instead; page may still be derived (e.g., 'pp. 12-14') for display. */
            page?: string | null;
            timestamp?: string | null;
            /**
             * @default en
             * @enum {string}
             */
            language: "en" | "el" | "mixed";
            categories?: string[];
            /**
             * @description Ordered list of enclosing heading strings from document root. Empty for content preceding the first heading. Required for chunks produced under the hierarchical chunking contract (chunking-contract.md, ADR-0009).
             * @default []
             */
            sectionPath: string[];
            /** @description 1-indexed PDF page number of the first ParsedBlock in this chunk. Required for chunks produced under the hierarchical chunking contract. */
            pageStart?: number | null;
            /** @description 1-indexed PDF page number of the last ParsedBlock in this chunk. Must be >= pageStart when both are set. */
            pageEnd?: number | null;
            /** @description References chunks.chunkId of the parent when this chunk was produced by a sentence-boundary split inside a single oversized parent (chunking-contract.md §Chunk boundaries). NULL for top-level chunks. The join key for the Phase 2 graph traversal layer (ADR-0006). */
            parentChunkId?: string | null;
            /** @description Optional 50–100-token document-context summary produced at ingestion time by a ModelRoute with purpose='context_prefix' (ADR-0009 Step 4, D-MDL-002). When set, the embedding input is contextPrefix + '\n\n' + text and the BM25 index uses the same concatenation. The pristine text field is unaffected and remains the canonical source for A6 quote-overlap. NULL on chunks ingested before Contextual Retrieval was enabled for the tenant (corpusVersion-pinned). */
            contextPrefix?: string | null;
            /** @description Versioned embedding model used at index time, e.g., 'openai:text-embedding-3-small@2024-03'. */
            embeddingModel: string;
            embeddingDimension: number;
            corpusVersion: string;
            reviewNote?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * CalendarProfile
         * @description Inline calendar profile stored on tenants.config.calendarProfile. Carries the version string used by cache-key.md (calendarVersion field). Per decision register row I, fixed-feast and Paschalion choices are independent.
         */
        "calendar-profile.schema": {
            /** @description YYYY-MM-DD.NN per docs/contracts/api-versioning.md. Bumped on every change to fixedFeastCalendar or paschalion. Drives cache-key calendarVersion. */
            version: string;
            /**
             * @description Which calendar governs fixed feasts (e.g., Nativity, Theophany).
             * @enum {string}
             */
            fixedFeastCalendar: "julian" | "revised_julian" | "gregorian";
            /**
             * @description Which Paschalion governs movable feasts. Independent of fixedFeastCalendar (decision register row I).
             * @enum {string}
             */
            paschalion: "julian" | "gregorian";
            /** @description Optional admin-facing label (e.g., 'Old Calendar (Julian)'). */
            displayLabel?: string | null;
            /** @description Optional free-text notes for content managers; never user-facing. */
            notes?: string | null;
        };
        /**
         * RunTrace
         * @description Full pipeline run trace persisted for every query that reaches A1. Used by /runs/{id}, admin query log, debugging, and safety review.
         */
        "run-trace.schema": {
            /** @description ULID; matches X-Run-Id header. */
            runId: string;
            tenantId: string;
            userId: string;
            sessionId?: string | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
            cacheHit: boolean;
            /** @description Ordered stage records. Each pipeline call produces one entry. */
            stages: {
                /** @enum {string} */
                stage: "a1_a2_query_analyzer" | "a3_retrieval" | "a4_evidence_packager" | "a5_composer" | "a6_verifier" | "cache_lookup" | "cache_store";
                /** Format: date-time */
                startedAt: string;
                /** Format: date-time */
                finishedAt: string;
                /** @enum {string} */
                outcome: "ok" | "fallback" | "error" | "skipped";
                modelRouteId?: string | null;
                promptTokens?: number | null;
                completionTokens?: number | null;
                errorCode?: string | null;
                /** @description Short structured token only. MUST NOT contain raw query text, raw answer text, raw chunk text, secrets, or any field on the redaction inventory in observability.md. Use details for any richer payload. */
                notes?: string | null;
                /** @description Sanitized stage-specific telemetry. MUST NOT contain raw query/answer/chunk text or any field on the redaction inventory in observability.md. Examples: a3_retrieval may include retrieved chunk count and adapter-level filter shape; a6_verifier MUST include per-citation quoteOverlapRatio and threshold used; provider stages may include count_estimated when token counts are estimated. Model-backed stages (a1_a2_query_analyzer, a5_composer, a6_verifier) SHOULD record promptVersion (and optionally promptId) identifying the /prompts registry entry used, so the trace is reproducible against the exact prompt text (GS-3). */
                details?: {
                    [key: string]: unknown;
                } | null;
            }[];
            usage: {
                servedAnswerCount: number;
                freshModelRunCount: number;
                promptTokens?: number;
                completionTokens?: number;
            };
            /** @enum {string|null} */
            finalHandling?: "answer" | "answer_with_disclaimer" | "reframe_to_teaching" | "block_with_redirect" | "insufficient_evidence" | null;
            /** @enum {string|null} */
            finalConfidenceTier?: "GREEN" | "YELLOW" | "RED" | null;
            verifierPassed?: boolean | null;
            evidencePacketRef?: string | null;
        };
        /**
         * FlaggedQuery
         * @description Captured query that hit RED, block_with_redirect, insufficient_evidence, or A6 verifier failure. Used for content gap analysis and safety review.
         */
        "flagged-query.schema": {
            flaggedQueryId: string;
            tenantId: string;
            userId: string;
            runId?: string | null;
            /** @description Redacted query text per ADR 0005. Raw text lives only in raw_sensitive_log when the row is sensitive. */
            queryTextRedacted: string;
            /** @description FK to encrypted raw_sensitive_log row when sensitive; admin-only, audited, 30-day retention. */
            rawSensitiveLogId?: string | null;
            /** @enum {string} */
            flagReason: "red_tier" | "insufficient_evidence" | "block_with_redirect" | "verifier_failed" | "hard_safety_trigger" | "user_reported";
            sensitivityPrimary?: string | null;
            riskFlags?: string[];
            /** @description Optional flagged-query embedding for clustering. Vector dimension matches the active embedding model. */
            embedding?: number[] | null;
            embeddingModel?: string | null;
            clusterId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * AuditEntry
         * @description Immutable audit row written for sensitive admin views, raw-sensitive-text reads, role escalations, prompt activations, model-route certifications, and corpus approval changes.
         */
        "audit-entry.schema": {
            auditId: string;
            tenantId: string;
            actorUserId: string;
            actorRole: string;
            /** @enum {string} */
            action: "raw_sensitive_view" | "chunk_approved" | "chunk_rejected" | "chunk_visibility_changed" | "source_approved" | "model_route_certified" | "prompt_version_activated" | "tenant_config_updated" | "safety_config_approved" | "safety_suite_run_completed" | "ci_safety_suite_passed" | "ci_tenant_isolation_passed" | "user_role_changed" | "data_export_requested" | "retention_purged" | "founder_phase2_signoff";
            /** @enum {string} */
            resourceType: "chunk" | "source" | "query_log" | "run" | "tenant" | "user" | "prompt_version" | "model_route" | "safety_suite_run" | "safety_config" | "ci_check";
            resourceId: string;
            details?: {
                [key: string]: unknown;
            };
            ipAddress?: string | null;
            /** Format: date-time */
            occurredAt: string;
        };
        /**
         * ModelRoute
         * @description Certified provider/model/prompt/schema combination eligible to serve production traffic. Per ADR 0004, only certified routes may be used.
         */
        "model-route.schema": {
            /** @description Format: <name>@<YYYY-MM-DD.NN>, e.g., 'a5_compose_anthropic@2026-05-01.1'. */
            routeId: string;
            /**
             * @description Which pipeline stage this route is certified for. 'rerank' is the cross-encoder reranker route (ADR-0012); 'retrieval_eval_judge' is the Ragas-style judge route for the retrieval-eval suite (docs/contracts/retrieval-eval-suite.md), certified separately from any answer-path route.
             * @enum {string}
             */
            purpose: "query_analyzer" | "compose" | "verifier_judge" | "embedding" | "rerank" | "retrieval_eval_judge";
            /**
             * @description Provider/model family. 'bge' (BAAI BGE-M3) is a T-009 embedding candidate served locally via fastembed/FlagEmbedding or a hosted endpoint.
             * @enum {string}
             */
            provider: "anthropic" | "openai" | "bge";
            model: string;
            promptVersion: string;
            /** @description GS-3 prompt-registry path stem identifying which prompt template tree under /prompts this route draws from, e.g. 'a1_classifier/en'. Optional during the Phase-1 bootstrap; combined with promptVersion it locates the exact /prompts/<promptId>/<version>.j2 file once the runtime prompt-loader (GS-3 follow-up) lands. */
            promptId?: string | null;
            schemaVersion: string;
            /** @default false */
            supportsPromptCache: boolean;
            /** @default false */
            supportsBatch: boolean;
            /** @default false */
            supportsJsonMode: boolean;
            /** @enum {string} */
            certificationStatus: "draft" | "experiment" | "certified" | "deprecated";
            /** @description Reference to the aggregate safety_suite_runs row that certified this route. A safety_suite_runs row groups all 20 individual run_traces.run_id entries produced by one pass of the canonical safety suite (tests/safety/test_20_queries.py). See ADR 0004 for the certification protocol and db-schema.md for the safety_suite_runs table shape. */
            safetySuiteRunId?: string | null;
            /** @description Reference to the retrieval_eval_runs row that certified this route's retrieval quality. The second binding gate for purpose IN ('embedding','rerank') routes (docs/contracts/retrieval-eval-suite.md), alongside safetySuiteRunId. NULL for routes whose purpose has no retrieval-eval gate. */
            retrievalEvalRunId?: string | null;
            certifiedBy?: string | null;
            /** Format: date-time */
            certifiedAt?: string | null;
            /** Format: date-time */
            deprecatedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * AnswerMode
         * @enum {string}
         */
        "answer-mode.schema": "consensus" | "institutional_policy" | "scholarly_dispute" | "pastoral_guidance" | "insufficient";
        /** ClassifiedQuery */
        "classified-query.schema": {
            rawQuery: string;
            reframedQuery?: string | null;
            answerMode: components["schemas"]["answer-mode.schema"];
            /**
             * @description A1's preliminary read of expected answerability before retrieval. The authoritative confidenceTier on EvidencePacket and VerifiedResponse is computed by A4 after evidence admission. Used only to short-circuit RED early-exit paths.
             * @enum {string}
             */
            preliminaryConfidenceTier: "GREEN" | "YELLOW" | "RED";
            /** @enum {string} */
            sensitivityPrimary: "normal" | "pastoral_advice" | "political" | "medical" | "comparative_religion" | "canonical_dispute" | "other_sensitive";
            riskFlags: ("self_harm" | "medical_emergency" | "canonical_dispute_active" | "minor_protection")[];
            /** @enum {string} */
            handling: "answer" | "answer_with_disclaimer" | "reframe_to_teaching" | "block_with_redirect" | "insufficient_evidence";
            /** @default false */
            reframingDisclosureRequired: boolean;
            classifierVersion?: string;
            /**
             * @description Optional A1 pre-classification of a block_with_redirect query into its bounded-fallback case class. Disambiguates wire-identical hard-safety cases (e.g. fabrication_attempt vs no_source_quote) so the /query hard-safety path emits the correct canonical bounded text; when absent, the path falls back to risk-flag / sensitivity heuristics.
             * @enum {unknown}
             */
            caseClass?: "fabrication_attempt" | "no_source_quote" | "political_voting" | "self_harm" | "medical_emergency" | null;
        };
        /** RetrievalPlan */
        "retrieval-plan.schema": {
            /** @description Phase 1 must equal classifiedQuery.reframedQuery ?? classifiedQuery.rawQuery. */
            semanticQuery: string;
            answerMode: components["schemas"]["answer-mode.schema"];
            /** @description Adapter-injected. The Qdrant adapter MUST overwrite this with Principal.tenantId regardless of the value emitted by A2; the field is present in the schema so generated client code can deserialize the plan, but a model-emitted value MUST NOT reach Qdrant. See docs/contracts/auth-context.md and docs/contracts/code-gen-guide.md. */
            tenantId: string;
            filters: {
                /** @description Adapter-injected. Always equals Principal.tenantId at the Qdrant call boundary; any other value is treated as a bug. */
                tenantId: string;
                /** @constant */
                approved: true;
                visibility?: string[];
                language?: string;
                categories?: string[];
            };
            boosts?: {
                field: string;
                value: string;
                weight: number;
            }[];
            /** @default 8 */
            k: number;
            /** @description Retrieval mode flags. Phase 1 default: vector-only. Hybrid and reranker are reserved for ADR-approved enablement. */
            retrieval?: {
                /** @default false */
                useBM25: boolean;
                /** @default false */
                useHybrid: boolean;
                reranker?: {
                    /** @default false */
                    enabled: boolean;
                    model?: string | null;
                };
            };
            /** @description Reserved for later ADR-approved graph-grounded expansion; null in Phase 1. */
            conceptExpansion?: null;
        };
        /** EvidencePacket */
        "evidence-packet.schema": {
            tenantId: string;
            corpusVersion: string;
            /** @enum {string} */
            confidenceTier: "GREEN" | "YELLOW" | "RED";
            admittedChunks: {
                chunkId: string;
                sourceId: string;
                title: string;
                work?: string;
                father?: string;
                text: string;
                score: number;
                page?: string | null;
                timestamp?: string | null;
                /** @constant */
                approved: true;
                /**
                 * @description Admitted evidence is restricted to user-facing visibility tiers. admin_only and suppressed chunks are never admittable per ADR 0001.
                 * @enum {string}
                 */
                visibility: "member" | "scholar";
                sourceHash: string;
                chunkHash: string;
            }[];
            suppressedChunkIds: string[];
            /**
             * @description Only approved edge IDs may appear here. Phase 1 emits an empty array.
             * @default []
             */
            lineageContext: {
                edgeId: string;
                relationType: string;
                /** @constant */
                approved: true;
                provenanceNote?: string;
            }[];
        };
        /**
         * Principal
         * @description Authenticated request principal. Built by core/middleware.py from a Clerk JWT. Required by every repository and service call.
         */
        "principal.schema": {
            /** @description Internal user id. */
            userId: string;
            /** @description Source-of-truth user id from Clerk. */
            clerkUserId: string;
            /** @description Internal tenant id. */
            tenantId: string;
            /** @description Clerk organization id mapped 1:1 to tenantId. */
            clerkOrgId: string;
            /** @enum {string} */
            role: "member" | "scholar" | "content_manager" | "admin" | "owner";
            scopes: ("query:read" | "corpus:read" | "corpus:write" | "corpus:approve" | "admin:queries:read" | "admin:flagged:read" | "admin:audit:read" | "admin:raw_sensitive:read" | "model_route:certify" | "tenant:config:read" | "tenant:config:write" | "billing:read")[];
            /**
             * @default us
             * @enum {string}
             */
            dataRegion: "us" | "eu";
        };
        /**
         * Tenant
         * @description Internal tenant record. Joined to Clerk org and Stripe customer.
         */
        "tenant.schema": {
            tenantId: string;
            name: string;
            clerkOrgId: string;
            stripeCustomerId?: string | null;
            /** @enum {string} */
            status: "active" | "suspended" | "trial" | "closed";
            /** @enum {string} */
            dataRegion: "us" | "eu";
            /** @default false */
            starterCorpusEnabled: boolean;
            /** @description Safe tenant configuration mirror of /tenant/config. The calendarProfile is stored inline so the cache-key path tenants.config.calendarProfile.version (per docs/contracts/cache-key.md) is satisfied without a join. */
            config?: {
                /** @enum {string} */
                tone?: "plain" | "pastoral" | "scholarly";
                /** @enum {string} */
                defaultAnswerLength?: "short" | "medium" | "long";
                citationStyle?: string;
                calendarProfile?: components["schemas"]["calendar-profile.schema"];
                starterCorpusEnabled?: boolean;
                /** @enum {string} */
                sensitiveHandlingStrictness?: "standard" | "strict";
                disclaimerTemplateId?: string | null;
                /**
                 * @description Tenant ecclesiastical jurisdiction. Independent of calendarProfile (e.g., a GOARCH-jurisdiction tenant may run a revised-Julian fixed-feast calendar with a Julian Paschalion). Surfaces in citation context; drives the institutional_policy answer mode in Phase 2+. Phase 1: optional; recorded but not retrieval-influential. Use 'other' with ecclesiasticalJurisdictionOther for any value not in this enum.
                 * @enum {string|null}
                 */
                ecclesiasticalJurisdiction?: null | "oca" | "rocor" | "ecumenical_patriarchate" | "goarch" | "moscow_patriarchate" | "antiochian" | "serbian" | "romanian" | "bulgarian" | "georgian" | "albanian" | "polish" | "czech_slovak" | "ukrainian_orthodox" | "japanese" | "coptic" | "ethiopian" | "eritrean" | "armenian" | "syriac" | "malankara" | "assyrian" | "monastic_athonite" | "monastic_other" | "academic" | "pan_orthodox" | "other";
                /** @description Free-text jurisdiction descriptor when ecclesiasticalJurisdiction == 'other'. Reviewer-facing; not parsed by retrieval or composition. Must be null when ecclesiasticalJurisdiction is any value other than 'other'. */
                ecclesiasticalJurisdictionOther?: string | null;
                configVersion?: string;
                /** @description System-managed pointer to the active corpus version for this tenant. Set by the ingestion service on cutover; surfaces in cache-key recipe and on GET /tenant/config (read-only). Not editable via PATCH /tenant/config. */
                corpusVersion?: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        /**
         * User
         * @description Internal user record. Source of truth for identity is Clerk; this row carries internal mapping and tenant binding.
         */
        "user.schema": {
            userId: string;
            clerkUserId: string;
            tenantId: string;
            /** Format: email */
            email?: string | null;
            displayName?: string | null;
            /** @enum {string} */
            role: "member" | "scholar" | "content_manager" | "admin" | "owner";
            /** @enum {string} */
            status: "active" | "invited" | "disabled";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt?: string | null;
        };
        /**
         * Source
         * @description Tenant corpus source document. Created by ingestion; chunks are produced from approved sources.
         */
        "source.schema": {
            sourceId: string;
            tenantId: string;
            title: string;
            father?: string | null;
            work?: string | null;
            /**
             * @default en
             * @enum {string}
             */
            language: "en" | "el" | "mixed";
            /** @enum {string} */
            sourceType: "pdf" | "txt" | "md" | "docx";
            /** @description SHA-256 of raw bytes before processing, per decision register row J. */
            sourceHash: string;
            /** @description Tool + version used for text extraction (e.g., 'pypdf@4.2.0'). */
            extractionMethod: string;
            /** @description Upstream corpus the source originated from. Drives Phase 3 cross-institution attribution and Phase 4 manuscript-partnership accounting. Use the catch-all 'tenant_upload' when no canonical upstream applies. The 'monastery_archive:<name>' prefix identifies a specific monastery archive (e.g., 'monastery_archive:simonopetra'). */
            corpusOrigin?: ((string | null | ("tlg" | "migne_pg" | "migne_pl" | "ccsg" | "sources_chretiennes" | "goarch_publications" | "oca_publications" | "antiochian_publications" | "rocor_publications" | "moscow_patriarchate_publications" | "romanian_patriarchate_publications" | "serbian_patriarchate_publications" | "ecumenical_patriarchate_publications" | "coptic_patriarchate_publications" | "ethiopian_patriarchate_publications" | "armenian_patriarchate_publications" | "syriac_patriarchate_publications" | "academic_journal" | "tenant_upload" | "other")) | null) | null | ("tlg" | "migne_pg" | "migne_pl" | "ccsg" | "sources_chretiennes" | "goarch_publications" | "oca_publications" | "antiochian_publications" | "rocor_publications" | "moscow_patriarchate_publications" | "romanian_patriarchate_publications" | "serbian_patriarchate_publications" | "ecumenical_patriarchate_publications" | "coptic_patriarchate_publications" | "ethiopian_patriarchate_publications" | "armenian_patriarchate_publications" | "syriac_patriarchate_publications" | "academic_journal" | "tenant_upload" | "other") | string;
            /**
             * @description Physical or digital provenance of the source text. Determines citation confidence and unblocks Phase 4 manuscript-witness graph work.
             * @enum {string|null}
             */
            digitizationProvenance?: null | "manuscript" | "manuscript_facsimile" | "critical_edition" | "scholarly_edition" | "paperback" | "hardcover" | "publisher_pdf" | "scanned_pdf" | "web_html" | "born_digital" | "audio_transcript" | "video_transcript" | "unknown";
            /** @default false */
            approved: boolean;
            approvalNote?: string | null;
            approvedBy?: string | null;
            /** Format: date-time */
            approvedAt?: string | null;
            corpusVersion: string;
            /** @description Free-form metadata: edition, translator, publisher, year, etc. */
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * Session
         * @description Conversation session for follow-up queries. The sessionHash is derived from sessionId+tenantId and contributes to cache keys for follow-ups so they do not share cache entries with standalone queries.
         */
        "session.schema": {
            sessionId: string;
            tenantId: string;
            userId: string;
            /** @description Stable hash derived from sessionId + tenantId; used in cache key for follow-ups only. */
            sessionHash: string;
            turnCount: number;
            /** Format: date-time */
            lastQueryAt?: string | null;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * BillingUsage
         * @description Per-tenant rolling usage row used by the Stripe metered meter. servedAnswerCount is the meter; freshModelRunCount is internal cost tracking only.
         */
        "billing-usage.schema": {
            tenantId: string;
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
            servedAnswerCount: number;
            freshModelRunCount: number;
            promptTokens?: number;
            completionTokens?: number;
            embeddingTokens?: number;
            stripeUsageRecordId?: string | null;
            /** Format: date-time */
            reportedAt?: string | null;
        };
    };
    responses: {
        /** @description Authentication failed. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Authorization failed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Request body failed validation. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Tenant has no approved chunks. */
        CorpusEmpty: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Rate limit exceeded. See `retryAfterSeconds`. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Tenant has exceeded its plan quota. */
        QuotaExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Upload type not supported. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Upload exceeds tenant size limit. */
        IngestTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Upload could not be processed. */
        IngestInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Webhook signature verification failed. */
        WebhookBadSignature: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Webhook idempotency key already processed. */
        WebhookReplay: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Optimistic concurrency check failed (e.g., If-Match did not match the current version). */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Unexpected error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "ok";
                        version?: string;
                    };
                };
            };
        };
    };
    submitQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    question: string;
                    answerMode?: components["schemas"]["AnswerMode"];
                    sessionId?: string;
                    /**
                     * @description When true, the response is delivered as Server-Sent Events with
                     *     `progress` events, ending with a single `done` event whose payload
                     *     is the full VerifiedResponse. Draft answer text is never streamed.
                     *     On a cache hit the orchestrator emits a single `done` event with
                     *     the cached VerifiedResponse and no intermediate `progress` events.
                     * @default false
                     */
                    streamProgress?: boolean;
                };
            };
        };
        responses: {
            /**
             * @description Verified answer or bounded fallback. When `streamProgress: true` is requested,
             *     the server may switch to a Server-Sent Events stream over the same path. SSE
             *     event payloads are typed against `components.schemas.ProgressEvent` (mirrored
             *     from `docs/schemas/progress-event.schema.json`); the SSE wire grammar lives in
             *     `docs/contracts/code-gen-guide.md` §Server-Sent Events because OpenAPI 3.1
             *     does not model the `text/event-stream` media type natively. The typed JSON
             *     contract on this response is the cache-hit and terminal `done`-event shape
             *     (a full `VerifiedResponse`).
             */
            200: {
                headers: {
                    /** @description ULID for this pipeline run. */
                    "X-Run-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verified-response.schema"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["QuotaExceeded"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["CorpusEmpty"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    uploadSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @enum {string} */
                    sourceType?: "pdf" | "txt" | "md" | "docx";
                    title?: string;
                    father?: string;
                    work?: string;
                    /** @enum {string} */
                    language?: "en" | "el" | "mixed";
                };
            };
        };
        responses: {
            /** @description Ingestion accepted and queued for approval. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        jobId: string;
                        sourceId: string;
                        /** @enum {string} */
                        status: "queued";
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["QuotaExceeded"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["IngestTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["IngestInvalid"];
            500: components["responses"]["InternalError"];
        };
    };
    getIngestJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description IngestJob status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ingest-job.schema"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listCorpus: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor. */
                cursor?: string;
                limit?: number;
                approved?: boolean;
                visibility?: "member" | "scholar" | "admin_only" | "suppressed";
                sourceId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of chunks scoped to the tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["chunk.schema"][];
                        nextCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    reviewChunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunkId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    approved?: boolean;
                    /** @enum {string} */
                    visibility?: "member" | "scholar" | "admin_only" | "suppressed";
                    reviewNote?: string;
                };
            };
        };
        responses: {
            /** @description Updated chunk. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["chunk.schema"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    getTenantConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Tenant safe configuration. The returned `configVersion` is the optimistic-concurrency token clients
             *     must echo back via the `If-Match` header on subsequent PATCH requests.
             */
            200: {
                headers: {
                    /** @description Equal to the returned `configVersion`. Convenience for HTTP caches. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        tone?: "plain" | "pastoral" | "scholarly";
                        /** @enum {string} */
                        defaultAnswerLength?: "short" | "medium" | "long";
                        citationStyle?: string;
                        calendarProfile?: components["schemas"]["calendar-profile.schema"];
                        starterCorpusEnabled?: boolean;
                        /** @enum {string} */
                        sensitiveHandlingStrictness?: "standard" | "strict";
                        disclaimerTemplateId?: string | null;
                        configVersion: string;
                        /**
                         * @description System-managed pointer to the active corpus version for this tenant. Set by the
                         *     ingestion service on cutover; never editable via PATCH /tenant/config. Surfaces
                         *     here so clients can detect cache invalidation. Null until the first ingestion
                         *     cutover succeeds.
                         */
                        readonly corpusVersion?: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    updateTenantConfig: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Optimistic concurrency token. Must equal the `configVersion` most recently returned by
                 *     `GET /tenant/config`. On mismatch the server returns 412 `precondition_failed` and the
                 *     client must re-read, merge, and retry.
                 */
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    tone?: "plain" | "pastoral" | "scholarly";
                    /** @enum {string} */
                    defaultAnswerLength?: "short" | "medium" | "long";
                    citationStyle?: string;
                    calendarProfile?: components["schemas"]["calendar-profile.schema"];
                    starterCorpusEnabled?: boolean;
                    /** @enum {string} */
                    sensitiveHandlingStrictness?: "standard" | "strict";
                    disclaimerTemplateId?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated safe tenant configuration. The new `configVersion` is returned for the next If-Match round-trip. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        configVersion: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RunTrace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["run-trace.schema"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listAdminQueries: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                handling?: string;
                confidenceTier?: "GREEN" | "YELLOW" | "RED";
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of run-trace summaries (sensitive query text redacted). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["run-trace.schema"][];
                        nextCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listFlaggedQueries: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                flagReason?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of flagged queries (redacted by default). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["flagged-query.schema"][];
                        nextCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listAuditEntries: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                action?: string;
                resourceType?: string;
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of audit entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["audit-entry.schema"][];
                        nextCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getAdminQueryRaw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw query payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    certifyModelRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Free-text rationale, persisted to audit row details. */
                    certificationNotes: string;
                };
            };
        };
        responses: {
            /** @description Route certified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["model-route.schema"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Route already certified or in an incompatible state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    stripeWebhook: {
        parameters: {
            query?: never;
            header: {
                "Stripe-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Accepted. The receiver acknowledges receipt and durably enqueues the event for processing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            401: components["responses"]["WebhookBadSignature"];
            409: components["responses"]["WebhookReplay"];
        };
    };
    clerkWebhook: {
        parameters: {
            query?: never;
            header: {
                "svix-id": string;
                "svix-timestamp": string;
                "svix-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Accepted. The receiver acknowledges receipt and durably enqueues the event for processing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            401: components["responses"]["WebhookBadSignature"];
            409: components["responses"]["WebhookReplay"];
        };
    };
    makeWebhook: {
        parameters: {
            query?: never;
            header?: {
                /** @description Reserved for Phase 2 activation; ignored in Phase 1. */
                "X-Make-Timestamp"?: string;
                /** @description Reserved for Phase 2 activation; ignored in Phase 1. */
                "X-Make-Nonce"?: string;
                /** @description Reserved for Phase 2 activation; ignored in Phase 1. */
                "X-Make-Signature"?: string;
                /** @description Reserved for Phase 2 activation; ignored in Phase 1. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Make.com webhook handler is deferred to Phase 2; activation requires founder sign-off and a Make.com integration spec. The endpoint exists today only to lock the URL contract. Returns ApiError with `code='feature_deferred'`. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
