[mypy]
python_version = 3.12
plugins = pydantic.mypy

[mypy-app.domain.*]
strict = True

[mypy-qdrant_client.*]
ignore_missing_imports = True

[mypy-pdfplumber.*]
ignore_missing_imports = True

[mypy-pytesseract.*]
ignore_missing_imports = True

[mypy-nltk.*]
ignore_missing_imports = True
