# generated by datamodel-codegen:
#   filename:  answer-mode.schema.json

from __future__ import annotations

from enum import Enum


class AnswerMode(Enum):
    consensus = 'consensus'
    institutional_policy = 'institutional_policy'
    scholarly_dispute = 'scholarly_dispute'
    pastoral_guidance = 'pastoral_guidance'
    insufficient = 'insufficient'
