# generated by datamodel-codegen:
#   filename:  api-error.schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class ApiError(BaseModel):
    """
    Canonical error envelope returned by every non-2xx response. Code values defined in docs/contracts/error-taxonomy.md.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(pattern=r'^[a-z][a-z0-9_]+$') = Field(
        ..., description='Stable machine-readable code from error-taxonomy.md.'
    )
    message: str = Field(
        ...,
        description='Human-readable, user-safe message. Never includes secrets, raw sensitive query text, or stack traces.',
    )
    trace_id: str = Field(
        ..., alias='traceId', description='ULID matching X-Run-Id; used to find logs.'
    )
    details: dict[str, Any] | None = Field(
        None,
        description='Optional structured details. Must not include sensitive fields.',
    )
    retryable: bool | None = False
    retry_after_seconds: conint(ge=0) | None = Field(None, alias='retryAfterSeconds')
