# generated by datamodel-codegen:
#   filename:  audit-entry.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Action(Enum):
    raw_sensitive_view = 'raw_sensitive_view'
    chunk_approved = 'chunk_approved'
    chunk_rejected = 'chunk_rejected'
    chunk_visibility_changed = 'chunk_visibility_changed'
    source_approved = 'source_approved'
    model_route_certified = 'model_route_certified'
    prompt_version_activated = 'prompt_version_activated'
    tenant_config_updated = 'tenant_config_updated'
    safety_config_approved = 'safety_config_approved'
    safety_suite_run_completed = 'safety_suite_run_completed'
    ci_safety_suite_passed = 'ci_safety_suite_passed'
    ci_tenant_isolation_passed = 'ci_tenant_isolation_passed'
    user_role_changed = 'user_role_changed'
    data_export_requested = 'data_export_requested'
    retention_purged = 'retention_purged'
    founder_phase2_signoff = 'founder_phase2_signoff'


class ResourceType(Enum):
    chunk = 'chunk'
    source = 'source'
    query_log = 'query_log'
    run = 'run'
    tenant = 'tenant'
    user = 'user'
    prompt_version = 'prompt_version'
    model_route = 'model_route'
    safety_suite_run = 'safety_suite_run'
    safety_config = 'safety_config'
    ci_check = 'ci_check'


class AuditEntry(BaseModel):
    """
    Immutable audit row written for sensitive admin views, raw-sensitive-text reads, role escalations, prompt activations, model-route certifications, and corpus approval changes.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    audit_id: str = Field(..., alias='auditId')
    tenant_id: str = Field(..., alias='tenantId')
    actor_user_id: str = Field(..., alias='actorUserId')
    actor_role: str = Field(..., alias='actorRole')
    action: Action
    resource_type: ResourceType = Field(..., alias='resourceType')
    resource_id: str = Field(..., alias='resourceId')
    details: dict[str, Any] | None = None
    ip_address: str | None = Field(None, alias='ipAddress')
    occurred_at: AwareDatetime = Field(..., alias='occurredAt')
