# generated by datamodel-codegen:
#   filename:  billing-usage.schema.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint


class BillingUsage(BaseModel):
    """
    Per-tenant rolling usage row used by the Stripe metered meter. servedAnswerCount is the meter; freshModelRunCount is internal cost tracking only.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    tenant_id: str = Field(..., alias='tenantId')
    period_start: AwareDatetime = Field(..., alias='periodStart')
    period_end: AwareDatetime = Field(..., alias='periodEnd')
    served_answer_count: conint(ge=0) = Field(..., alias='servedAnswerCount')
    fresh_model_run_count: conint(ge=0) = Field(..., alias='freshModelRunCount')
    prompt_tokens: conint(ge=0) | None = Field(None, alias='promptTokens')
    completion_tokens: conint(ge=0) | None = Field(None, alias='completionTokens')
    embedding_tokens: conint(ge=0) | None = Field(None, alias='embeddingTokens')
    stripe_usage_record_id: str | None = Field(None, alias='stripeUsageRecordId')
    reported_at: AwareDatetime | None = Field(None, alias='reportedAt')
