# generated by datamodel-codegen:
#   filename:  calendar-profile.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, constr


class FixedFeastCalendar(Enum):
    """
    Which calendar governs fixed feasts (e.g., Nativity, Theophany).
    """

    julian = 'julian'
    revised_julian = 'revised_julian'
    gregorian = 'gregorian'


class Paschalion(Enum):
    """
    Which Paschalion governs movable feasts. Independent of fixedFeastCalendar (decision register row I).
    """

    julian = 'julian'
    gregorian = 'gregorian'


class CalendarProfile(BaseModel):
    """
    Inline calendar profile stored on tenants.config.calendarProfile. Carries the version string used by cache-key.md (calendarVersion field). Per decision register row I, fixed-feast and Paschalion choices are independent.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    version: constr(pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}\.[0-9]+$') = Field(
        ...,
        description='YYYY-MM-DD.NN per docs/contracts/api-versioning.md. Bumped on every change to fixedFeastCalendar or paschalion. Drives cache-key calendarVersion.',
    )
    fixed_feast_calendar: FixedFeastCalendar = Field(
        ...,
        alias='fixedFeastCalendar',
        description='Which calendar governs fixed feasts (e.g., Nativity, Theophany).',
    )
    paschalion: Paschalion = Field(
        ...,
        description='Which Paschalion governs movable feasts. Independent of fixedFeastCalendar (decision register row I).',
    )
    display_label: str | None = Field(
        None,
        alias='displayLabel',
        description="Optional admin-facing label (e.g., 'Old Calendar (Julian)').",
    )
    notes: str | None = Field(
        None,
        description='Optional free-text notes for content managers; never user-facing.',
    )
