# generated by datamodel-codegen:
#   filename:  chunk.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class Visibility(Enum):
    member = 'member'
    scholar = 'scholar'
    admin_only = 'admin_only'
    suppressed = 'suppressed'


class Language(Enum):
    en = 'en'
    el = 'el'
    mixed = 'mixed'


class Chunk(BaseModel):
    """
    Indexed retrievable chunk. The Qdrant payload mirrors the same fields plus the embedding vector.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    chunk_id: str = Field(..., alias='chunkId')
    source_id: str = Field(..., alias='sourceId')
    tenant_id: str = Field(..., alias='tenantId')
    text: constr(min_length=1)
    chunk_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$') = Field(..., alias='chunkHash')
    approved: bool
    visibility: Visibility
    father: str | None = None
    work: str | None = None
    page: str | None = Field(
        None,
        description="Legacy single-page citation string. New chunks emitted under the hierarchical chunking contract populate pageStart/pageEnd instead; page may still be derived (e.g., 'pp. 12-14') for display.",
    )
    timestamp: str | None = None
    language: Language | None = 'en'
    categories: list[str] | None = None
    section_path: list[str] | None = Field(
        [],
        alias='sectionPath',
        description='Ordered list of enclosing heading strings from document root. Empty for content preceding the first heading. Required for chunks produced under the hierarchical chunking contract (chunking-contract.md, ADR-0009).',
    )
    page_start: conint(ge=1) | None = Field(
        None,
        alias='pageStart',
        description='1-indexed PDF page number of the first ParsedBlock in this chunk. Required for chunks produced under the hierarchical chunking contract.',
    )
    page_end: conint(ge=1) | None = Field(
        None,
        alias='pageEnd',
        description='1-indexed PDF page number of the last ParsedBlock in this chunk. Must be >= pageStart when both are set.',
    )
    parent_chunk_id: str | None = Field(
        None,
        alias='parentChunkId',
        description='References chunks.chunkId of the parent when this chunk was produced by a sentence-boundary split inside a single oversized parent (chunking-contract.md §Chunk boundaries). NULL for top-level chunks. The join key for the Phase 2 graph traversal layer (ADR-0006).',
    )
    context_prefix: constr(max_length=200) | None = Field(
        None,
        alias='contextPrefix',
        description="Optional 50–100-token document-context summary produced at ingestion time by a ModelRoute with purpose='context_prefix' (ADR-0009 Step 4, D-MDL-002). When set, the embedding input is contextPrefix + '\\n\\n' + text and the BM25 index uses the same concatenation. The pristine text field is unaffected and remains the canonical source for A6 quote-overlap. NULL on chunks ingested before Contextual Retrieval was enabled for the tenant (corpusVersion-pinned).",
    )
    embedding_model: str = Field(
        ...,
        alias='embeddingModel',
        description="Versioned embedding model used at index time, e.g., 'openai:text-embedding-3-small@2024-03'.",
    )
    embedding_dimension: conint(ge=1) = Field(..., alias='embeddingDimension')
    corpus_version: str = Field(..., alias='corpusVersion')
    review_note: str | None = Field(None, alias='reviewNote')
    created_at: AwareDatetime = Field(..., alias='createdAt')
