# generated by datamodel-codegen:
#   filename:  classified-query.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, constr

from . import answer_mode_schema


class PreliminaryConfidenceTier(Enum):
    """
    A1's preliminary read of expected answerability before retrieval. The authoritative confidenceTier on EvidencePacket and VerifiedResponse is computed by A4 after evidence admission. Used only to short-circuit RED early-exit paths.
    """

    green = 'GREEN'
    yellow = 'YELLOW'
    red = 'RED'


class SensitivityPrimary(Enum):
    normal = 'normal'
    pastoral_advice = 'pastoral_advice'
    political = 'political'
    medical = 'medical'
    comparative_religion = 'comparative_religion'
    canonical_dispute = 'canonical_dispute'
    other_sensitive = 'other_sensitive'


class RiskFlag(Enum):
    self_harm = 'self_harm'
    medical_emergency = 'medical_emergency'
    canonical_dispute_active = 'canonical_dispute_active'
    minor_protection = 'minor_protection'


class Handling(Enum):
    answer = 'answer'
    answer_with_disclaimer = 'answer_with_disclaimer'
    reframe_to_teaching = 'reframe_to_teaching'
    block_with_redirect = 'block_with_redirect'
    insufficient_evidence = 'insufficient_evidence'


class CaseClass(Enum):
    """
    Optional A1 pre-classification of a block_with_redirect query into its bounded-fallback case class. Disambiguates wire-identical hard-safety cases (e.g. fabrication_attempt vs no_source_quote) so the /query hard-safety path emits the correct canonical bounded text; when absent, the path falls back to risk-flag / sensitivity heuristics.
    """

    fabrication_attempt = 'fabrication_attempt'
    no_source_quote = 'no_source_quote'
    political_voting = 'political_voting'
    self_harm = 'self_harm'
    medical_emergency = 'medical_emergency'
    none_type_none = None


class ClassifiedQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    raw_query: constr(min_length=1) = Field(..., alias='rawQuery')
    reframed_query: str | None = Field(None, alias='reframedQuery')
    answer_mode: answer_mode_schema.AnswerMode = Field(..., alias='answerMode')
    preliminary_confidence_tier: PreliminaryConfidenceTier = Field(
        ...,
        alias='preliminaryConfidenceTier',
        description="A1's preliminary read of expected answerability before retrieval. The authoritative confidenceTier on EvidencePacket and VerifiedResponse is computed by A4 after evidence admission. Used only to short-circuit RED early-exit paths.",
    )
    sensitivity_primary: SensitivityPrimary = Field(..., alias='sensitivityPrimary')
    risk_flags: list[RiskFlag] = Field(..., alias='riskFlags')
    handling: Handling
    reframing_disclosure_required: (
        bool | None
    ) = Field(False, alias='reframingDisclosureRequired')
    classifier_version: str | None = Field(None, alias='classifierVersion')
    case_class: CaseClass | None = Field(
        None,
        alias='caseClass',
        description='Optional A1 pre-classification of a block_with_redirect query into its bounded-fallback case class. Disambiguates wire-identical hard-safety cases (e.g. fabrication_attempt vs no_source_quote) so the /query hard-safety path emits the correct canonical bounded text; when absent, the path falls back to risk-flag / sensitivity heuristics.',
    )
