# generated by datamodel-codegen:
#   filename:  evidence-packet.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat


class ConfidenceTier(Enum):
    green = 'GREEN'
    yellow = 'YELLOW'
    red = 'RED'


class Visibility(Enum):
    """
    Admitted evidence is restricted to user-facing visibility tiers. admin_only and suppressed chunks are never admittable per ADR 0001.
    """

    member = 'member'
    scholar = 'scholar'


class AdmittedChunk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chunk_id: str = Field(..., alias='chunkId')
    source_id: str = Field(..., alias='sourceId')
    title: str
    work: str | None = None
    father: str | None = None
    text: str
    score: confloat(ge=0.0, le=1.0)
    page: str | None = None
    timestamp: str | None = None
    approved: Literal[True]
    visibility: Visibility = Field(
        ...,
        description='Admitted evidence is restricted to user-facing visibility tiers. admin_only and suppressed chunks are never admittable per ADR 0001.',
    )
    source_hash: str = Field(..., alias='sourceHash')
    chunk_hash: str = Field(..., alias='chunkHash')


class LineageContextItem(BaseModel):
    edge_id: str = Field(..., alias='edgeId')
    relation_type: str = Field(..., alias='relationType')
    approved: Literal[True]
    provenance_note: str | None = Field(None, alias='provenanceNote')


class EvidencePacket(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tenant_id: str = Field(..., alias='tenantId')
    corpus_version: str = Field(..., alias='corpusVersion')
    confidence_tier: ConfidenceTier = Field(..., alias='confidenceTier')
    admitted_chunks: list[AdmittedChunk] = Field(..., alias='admittedChunks')
    suppressed_chunk_ids: list[str] = Field(..., alias='suppressedChunkIds')
    lineage_context: list[LineageContextItem] | None = Field(
        [],
        alias='lineageContext',
        description='Only approved edge IDs may appear here. Phase 1 emits an empty array.',
        validate_default=True,
    )
