# generated by datamodel-codegen:
#   filename:  flagged-query.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class FlagReason(Enum):
    red_tier = 'red_tier'
    insufficient_evidence = 'insufficient_evidence'
    block_with_redirect = 'block_with_redirect'
    verifier_failed = 'verifier_failed'
    hard_safety_trigger = 'hard_safety_trigger'
    user_reported = 'user_reported'


class FlaggedQuery(BaseModel):
    """
    Captured query that hit RED, block_with_redirect, insufficient_evidence, or A6 verifier failure. Used for content gap analysis and safety review.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    flagged_query_id: str = Field(..., alias='flaggedQueryId')
    tenant_id: str = Field(..., alias='tenantId')
    user_id: str = Field(..., alias='userId')
    run_id: str | None = Field(None, alias='runId')
    query_text_redacted: str = Field(
        ...,
        alias='queryTextRedacted',
        description='Redacted query text per ADR 0005. Raw text lives only in raw_sensitive_log when the row is sensitive.',
    )
    raw_sensitive_log_id: str | None = Field(
        None,
        alias='rawSensitiveLogId',
        description='FK to encrypted raw_sensitive_log row when sensitive; admin-only, audited, 30-day retention.',
    )
    flag_reason: FlagReason = Field(..., alias='flagReason')
    sensitivity_primary: str | None = Field(None, alias='sensitivityPrimary')
    risk_flags: list[str] | None = Field(None, alias='riskFlags')
    embedding: list[float] | None = Field(
        None,
        description='Optional flagged-query embedding for clustering. Vector dimension matches the active embedding model.',
    )
    embedding_model: str | None = Field(None, alias='embeddingModel')
    cluster_id: str | None = Field(None, alias='clusterId')
    created_at: AwareDatetime = Field(..., alias='createdAt')
