# generated by datamodel-codegen:
#   filename:  ingest-job.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint


class Status(Enum):
    queued = 'queued'
    extracting = 'extracting'
    chunking = 'chunking'
    embedding = 'embedding'
    awaiting_review = 'awaiting_review'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class Progress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stage: str | None = None
    completed: conint(ge=0) | None = None
    total: conint(ge=0) | None = None


class IngestJob(BaseModel):
    """
    Async ingestion job tracking upload → extract → chunk → embed → review-queue.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    job_id: str = Field(..., alias='jobId')
    tenant_id: str = Field(..., alias='tenantId')
    user_id: str = Field(..., alias='userId')
    source_id: str = Field(..., alias='sourceId')
    status: Status
    progress: Progress | None = None
    error_code: str | None = Field(None, alias='errorCode')
    error_message: str | None = Field(None, alias='errorMessage')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    started_at: AwareDatetime | None = Field(None, alias='startedAt')
    finished_at: AwareDatetime | None = Field(None, alias='finishedAt')
