# generated by datamodel-codegen:
#   filename:  model-route.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class Purpose(Enum):
    """
    Which pipeline stage this route is certified for. 'rerank' is the cross-encoder reranker route (ADR-0012); 'retrieval_eval_judge' is the Ragas-style judge route for the retrieval-eval suite (docs/contracts/retrieval-eval-suite.md), certified separately from any answer-path route.
    """

    query_analyzer = 'query_analyzer'
    compose = 'compose'
    verifier_judge = 'verifier_judge'
    embedding = 'embedding'
    rerank = 'rerank'
    retrieval_eval_judge = 'retrieval_eval_judge'


class Provider(Enum):
    """
    Provider/model family. 'bge' (BAAI BGE-M3) is a T-009 embedding candidate served locally via fastembed/FlagEmbedding or a hosted endpoint.
    """

    anthropic = 'anthropic'
    openai = 'openai'
    bge = 'bge'


class CertificationStatus(Enum):
    draft = 'draft'
    experiment = 'experiment'
    certified = 'certified'
    deprecated = 'deprecated'


class ModelRoute(BaseModel):
    """
    Certified provider/model/prompt/schema combination eligible to serve production traffic. Per ADR 0004, only certified routes may be used.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    route_id: constr(pattern=r'^[a-z][a-z0-9_]+@[0-9]{4}-[0-9]{2}-[0-9]{2}\.[0-9]+$') = (
        Field(
            ...,
            alias='routeId',
            description="Format: <name>@<YYYY-MM-DD.NN>, e.g., 'a5_compose_anthropic@2026-05-01.1'.",
        )
    )
    purpose: Purpose = Field(
        ...,
        description="Which pipeline stage this route is certified for. 'rerank' is the cross-encoder reranker route (ADR-0012); 'retrieval_eval_judge' is the Ragas-style judge route for the retrieval-eval suite (docs/contracts/retrieval-eval-suite.md), certified separately from any answer-path route.",
    )
    provider: Provider = Field(
        ...,
        description="Provider/model family. 'bge' (BAAI BGE-M3) is a T-009 embedding candidate served locally via fastembed/FlagEmbedding or a hosted endpoint.",
    )
    model: str
    prompt_version: str = Field(..., alias='promptVersion')
    prompt_id: str | None = Field(
        None,
        alias='promptId',
        description="GS-3 prompt-registry path stem identifying which prompt template tree under /prompts this route draws from, e.g. 'a1_classifier/en'. Optional during the Phase-1 bootstrap; combined with promptVersion it locates the exact /prompts/<promptId>/<version>.j2 file once the runtime prompt-loader (GS-3 follow-up) lands.",
    )
    schema_version: str = Field(..., alias='schemaVersion')
    supports_prompt_cache: bool | None = Field(False, alias='supportsPromptCache')
    supports_batch: bool | None = Field(False, alias='supportsBatch')
    supports_json_mode: bool | None = Field(False, alias='supportsJsonMode')
    certification_status: CertificationStatus = Field(..., alias='certificationStatus')
    safety_suite_run_id: str | None = Field(
        None,
        alias='safetySuiteRunId',
        description='Reference to the aggregate safety_suite_runs row that certified this route. A safety_suite_runs row groups all 20 individual run_traces.run_id entries produced by one pass of the canonical safety suite (tests/safety/test_20_queries.py). See ADR 0004 for the certification protocol and db-schema.md for the safety_suite_runs table shape.',
    )
    retrieval_eval_run_id: str | None = Field(
        None,
        alias='retrievalEvalRunId',
        description="Reference to the retrieval_eval_runs row that certified this route's retrieval quality. The second binding gate for purpose IN ('embedding','rerank') routes (docs/contracts/retrieval-eval-suite.md), alongside safetySuiteRunId. NULL for routes whose purpose has no retrieval-eval gate.",
    )
    certified_by: str | None = Field(None, alias='certifiedBy')
    certified_at: AwareDatetime | None = Field(None, alias='certifiedAt')
    deprecated_at: AwareDatetime | None = Field(None, alias='deprecatedAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
