# generated by datamodel-codegen:
#   filename:  parsed-block.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, PositiveFloat, conint, constr


class BlockType(Enum):
    """
    Best-effort classification. 'other' is the catch-all for content the parser cannot confidently classify (page numbers, running headers, decorative elements).
    """

    heading = 'heading'
    paragraph = 'paragraph'
    footnote = 'footnote'
    caption = 'caption'
    other = 'other'


class ParsedBlock(BaseModel):
    """
    A single typographic block emitted by a Parser (see docs/contracts/parser-interface.md). The chunking service consumes these to detect headings and assemble Chunks per docs/contracts/chunking-contract.md.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1) = Field(
        ...,
        description="The block's text content. Whitespace-only blocks must be omitted, not emitted with empty or whitespace text.",
    )
    block_type: BlockType = Field(
        ...,
        alias='blockType',
        description="Best-effort classification. 'other' is the catch-all for content the parser cannot confidently classify (page numbers, running headers, decorative elements).",
    )
    font_size: PositiveFloat | None = Field(
        None,
        alias='fontSize',
        description='Font size in PDF points. Required when parser.supports_typography is True; null permitted only on the OCR path (TesseractParser).',
    )
    bold: bool = Field(
        ...,
        description='True when the parser confidently identifies the block as bold. False is the safe default for parsers that cannot detect weight (OCR path).',
    )
    bbox: list[float] | None = Field(
        None,
        description='[x0, y0, x1, y1] in PDF points. Null permitted only on the OCR path.',
        max_length=4,
        min_length=4,
    )
    page_num: conint(ge=1) = Field(
        ...,
        alias='pageNum',
        description='1-indexed PDF page number. Must match the enclosing ParsedPage.page_num.',
    )
