# generated by datamodel-codegen:
#   filename:  principal.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Role(Enum):
    member = 'member'
    scholar = 'scholar'
    content_manager = 'content_manager'
    admin = 'admin'
    owner = 'owner'


class Scope(Enum):
    query_read = 'query:read'
    corpus_read = 'corpus:read'
    corpus_write = 'corpus:write'
    corpus_approve = 'corpus:approve'
    admin_queries_read = 'admin:queries:read'
    admin_flagged_read = 'admin:flagged:read'
    admin_audit_read = 'admin:audit:read'
    admin_raw_sensitive_read = 'admin:raw_sensitive:read'
    model_route_certify = 'model_route:certify'
    tenant_config_read = 'tenant:config:read'
    tenant_config_write = 'tenant:config:write'
    billing_read = 'billing:read'


class DataRegion(Enum):
    us = 'us'
    eu = 'eu'


class Principal(BaseModel):
    """
    Authenticated request principal. Built by core/middleware.py from a Clerk JWT. Required by every repository and service call.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    user_id: str = Field(..., alias='userId', description='Internal user id.')
    clerk_user_id: str = Field(
        ..., alias='clerkUserId', description='Source-of-truth user id from Clerk.'
    )
    tenant_id: str = Field(..., alias='tenantId', description='Internal tenant id.')
    clerk_org_id: str = Field(
        ...,
        alias='clerkOrgId',
        description='Clerk organization id mapped 1:1 to tenantId.',
    )
    role: Role
    scopes: list[Scope]
    data_region: DataRegion | None = Field('us', alias='dataRegion')
