# generated by datamodel-codegen:
#   filename:  progress-event.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint

from . import api_error_schema, verified_response_schema


class Stage(Enum):
    """
    Canonical stage identifier. Matches the run-trace.schema.json stages enum subset that represents substantive pipeline work (cache_lookup and cache_store are recorded in the run trace but never surfaced as progress events to keep cache hits non-leaky).
    """

    a1_a2_query_analyzer = 'a1_a2_query_analyzer'
    a3_retrieval = 'a3_retrieval'
    a4_evidence_packager = 'a4_evidence_packager'
    a5_composer = 'a5_composer'
    a6_verifier = 'a6_verifier'


class ProgressVariant(BaseModel):
    """
    SSE 'event: progress' payload. Emitted at the start of each substantive pipeline stage during a fresh run. Never emitted on a cache hit.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    stage: Stage = Field(
        ...,
        description='Canonical stage identifier. Matches the run-trace.schema.json stages enum subset that represents substantive pipeline work (cache_lookup and cache_store are recorded in the run trace but never surfaced as progress events to keep cache hits non-leaky).',
    )
    elapsed_ms: conint(ge=0) = Field(
        ...,
        alias='elapsedMs',
        description='Cumulative milliseconds since request receipt, measured server-side. Monotonic across events within a single run. The client may layer its own arrival timestamp on top (for UI freshness signals) but should not reorder events by client time.',
    )
    model_route_id: str | None = Field(
        None,
        alias='modelRouteId',
        description='Optional. Certified ModelRoute.routeId for stages that called a provider (typically a1_a2_query_analyzer, a5_composer, and the optional a6_verifier judge). Omitted for deterministic stages (a3_retrieval, a4_evidence_packager) and when the run path did not invoke a model.',
    )


class ErrorVariant(RootModel[api_error_schema.ApiError]):
    root: api_error_schema.ApiError = Field(
        ...,
        description="SSE 'event: error' payload. Emitted at most once and terminates the stream. The shape is the standard ApiError envelope so client error handling is uniform across the JSON-response and SSE-response paths.",
    )


class DoneVariant(RootModel[verified_response_schema.VerifiedResponse]):
    root: verified_response_schema.VerifiedResponse = Field(
        ...,
        description="SSE 'event: done' payload. Emitted exactly once at the terminal stage of every run (fresh or cache hit). The payload is the full VerifiedResponse including citations, runTrace, and verification.passed.",
    )


class ProgressEvent(RootModel[ProgressVariant | DoneVariant | ErrorVariant]):
    root: ProgressVariant | DoneVariant | ErrorVariant = Field(
        ...,
        description="Typed JSON payload (the SSE 'data:' line) for events emitted on POST /query when streamProgress=true. The SSE 'event:' line names the variant (progress | done | error). Each variant is validated against the corresponding $defs entry. Progress events are emitted zero or more times during a fresh model run; a single terminal done event carries the full VerifiedResponse; an error event may terminate the stream with a typed ApiError. Cache hits emit a single done event with no preceding progress events. See docs/contracts/code-gen-guide.md section Server-Sent Events for the wire format and docs/contracts/frontend-components.md for the StageStatus consumer.",
        title='ProgressEvent',
    )
