# generated by datamodel-codegen:
#   filename:  retrieval-plan.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, conint

from . import answer_mode_schema


class Filters(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tenant_id: str = Field(
        ...,
        alias='tenantId',
        description='Adapter-injected. Always equals Principal.tenantId at the Qdrant call boundary; any other value is treated as a bug.',
    )
    approved: Literal[True]
    visibility: list[str] | None = None
    language: str | None = None
    categories: list[str] | None = None


class Boost(BaseModel):
    field: str
    value: str
    weight: float


class Reranker(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool | None = False
    model: str | None = None


class Retrieval(BaseModel):
    """
    Retrieval mode flags. Phase 1 default: vector-only. Hybrid and reranker are reserved for ADR-approved enablement.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    use_bm25: bool | None = Field(False, alias='useBM25')
    use_hybrid: bool | None = Field(False, alias='useHybrid')
    reranker: Reranker | None = None


class RetrievalPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    semantic_query: str = Field(
        ...,
        alias='semanticQuery',
        description='Phase 1 must equal classifiedQuery.reframedQuery ?? classifiedQuery.rawQuery.',
    )
    answer_mode: answer_mode_schema.AnswerMode = Field(..., alias='answerMode')
    tenant_id: str = Field(
        ...,
        alias='tenantId',
        description='Adapter-injected. The Qdrant adapter MUST overwrite this with Principal.tenantId regardless of the value emitted by A2; the field is present in the schema so generated client code can deserialize the plan, but a model-emitted value MUST NOT reach Qdrant. See docs/contracts/auth-context.md and docs/contracts/code-gen-guide.md.',
    )
    filters: Filters
    boosts: list[Boost] | None = None
    k: conint(ge=1, le=20)
    retrieval: Retrieval | None = Field(
        None,
        description='Retrieval mode flags. Phase 1 default: vector-only. Hybrid and reranker are reserved for ADR-approved enablement.',
    )
    concept_expansion: None = Field(
        None,
        alias='conceptExpansion',
        description='Reserved for later ADR-approved graph-grounded expansion; null in Phase 1.',
    )
