# generated by datamodel-codegen:
#   filename:  run-trace.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class Stage(Enum):
    a1_a2_query_analyzer = 'a1_a2_query_analyzer'
    a3_retrieval = 'a3_retrieval'
    a4_evidence_packager = 'a4_evidence_packager'
    a5_composer = 'a5_composer'
    a6_verifier = 'a6_verifier'
    cache_lookup = 'cache_lookup'
    cache_store = 'cache_store'


class Outcome(Enum):
    ok = 'ok'
    fallback = 'fallback'
    error = 'error'
    skipped = 'skipped'


class Stage1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stage: Stage
    started_at: AwareDatetime = Field(..., alias='startedAt')
    finished_at: AwareDatetime = Field(..., alias='finishedAt')
    outcome: Outcome
    model_route_id: str | None = Field(None, alias='modelRouteId')
    prompt_tokens: conint(ge=0) | None = Field(None, alias='promptTokens')
    completion_tokens: conint(ge=0) | None = Field(None, alias='completionTokens')
    error_code: str | None = Field(None, alias='errorCode')
    notes: constr(max_length=256) | None = Field(
        None,
        description='Short structured token only. MUST NOT contain raw query text, raw answer text, raw chunk text, secrets, or any field on the redaction inventory in observability.md. Use details for any richer payload.',
    )
    details: dict[str, Any] | None = Field(
        None,
        description='Sanitized stage-specific telemetry. MUST NOT contain raw query/answer/chunk text or any field on the redaction inventory in observability.md. Examples: a3_retrieval may include retrieved chunk count and adapter-level filter shape; a6_verifier MUST include per-citation quoteOverlapRatio and threshold used; provider stages may include count_estimated when token counts are estimated. Model-backed stages (a1_a2_query_analyzer, a5_composer, a6_verifier) SHOULD record promptVersion (and optionally promptId) identifying the /prompts registry entry used, so the trace is reproducible against the exact prompt text (GS-3).',
    )


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    served_answer_count: conint(ge=0, le=1) = Field(..., alias='servedAnswerCount')
    fresh_model_run_count: conint(ge=0, le=1) = Field(..., alias='freshModelRunCount')
    prompt_tokens: conint(ge=0) | None = Field(None, alias='promptTokens')
    completion_tokens: conint(ge=0) | None = Field(None, alias='completionTokens')


class FinalHandling(Enum):
    answer = 'answer'
    answer_with_disclaimer = 'answer_with_disclaimer'
    reframe_to_teaching = 'reframe_to_teaching'
    block_with_redirect = 'block_with_redirect'
    insufficient_evidence = 'insufficient_evidence'
    none_type_none = None


class FinalConfidenceTier(Enum):
    green = 'GREEN'
    yellow = 'YELLOW'
    red = 'RED'
    none_type_none = None


class RunTrace(BaseModel):
    """
    Full pipeline run trace persisted for every query that reaches A1. Used by /runs/{id}, admin query log, debugging, and safety review.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    run_id: str = Field(
        ..., alias='runId', description='ULID; matches X-Run-Id header.'
    )
    tenant_id: str = Field(..., alias='tenantId')
    user_id: str = Field(..., alias='userId')
    session_id: str | None = Field(None, alias='sessionId')
    started_at: AwareDatetime = Field(..., alias='startedAt')
    finished_at: AwareDatetime | None = Field(None, alias='finishedAt')
    cache_hit: bool = Field(..., alias='cacheHit')
    stages: list[Stage1] = Field(
        ..., description='Ordered stage records. Each pipeline call produces one entry.'
    )
    usage: Usage
    final_handling: FinalHandling | None = Field(None, alias='finalHandling')
    final_confidence_tier: FinalConfidenceTier | None = Field(
        None, alias='finalConfidenceTier'
    )
    verifier_passed: bool | None = Field(None, alias='verifierPassed')
    evidence_packet_ref: str | None = Field(None, alias='evidencePacketRef')
