# generated by datamodel-codegen:
#   filename:  session.schema.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint


class Session(BaseModel):
    """
    Conversation session for follow-up queries. The sessionHash is derived from sessionId+tenantId and contributes to cache keys for follow-ups so they do not share cache entries with standalone queries.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: str = Field(..., alias='sessionId')
    tenant_id: str = Field(..., alias='tenantId')
    user_id: str = Field(..., alias='userId')
    session_hash: str = Field(
        ...,
        alias='sessionHash',
        description='Stable hash derived from sessionId + tenantId; used in cache key for follow-ups only.',
    )
    turn_count: conint(ge=0) = Field(..., alias='turnCount')
    last_query_at: AwareDatetime | None = Field(None, alias='lastQueryAt')
    expires_at: AwareDatetime | None = Field(None, alias='expiresAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
