# generated by datamodel-codegen:
#   filename:  source.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class Language(Enum):
    en = 'en'
    el = 'el'
    mixed = 'mixed'


class SourceType(Enum):
    pdf = 'pdf'
    txt = 'txt'
    md = 'md'
    docx = 'docx'


class CorpusOrigin(Enum):
    """
    Upstream corpus the source originated from. Drives Phase 3 cross-institution attribution and Phase 4 manuscript-partnership accounting. Use the catch-all 'tenant_upload' when no canonical upstream applies. The 'monastery_archive:<name>' prefix identifies a specific monastery archive (e.g., 'monastery_archive:simonopetra').
    """

    tlg = 'tlg'
    migne_pg = 'migne_pg'
    migne_pl = 'migne_pl'
    ccsg = 'ccsg'
    sources_chretiennes = 'sources_chretiennes'
    goarch_publications = 'goarch_publications'
    oca_publications = 'oca_publications'
    antiochian_publications = 'antiochian_publications'
    rocor_publications = 'rocor_publications'
    moscow_patriarchate_publications = 'moscow_patriarchate_publications'
    romanian_patriarchate_publications = 'romanian_patriarchate_publications'
    serbian_patriarchate_publications = 'serbian_patriarchate_publications'
    ecumenical_patriarchate_publications = 'ecumenical_patriarchate_publications'
    coptic_patriarchate_publications = 'coptic_patriarchate_publications'
    ethiopian_patriarchate_publications = 'ethiopian_patriarchate_publications'
    armenian_patriarchate_publications = 'armenian_patriarchate_publications'
    syriac_patriarchate_publications = 'syriac_patriarchate_publications'
    academic_journal = 'academic_journal'
    tenant_upload = 'tenant_upload'
    other = 'other'


class DigitizationProvenance(Enum):
    """
    Physical or digital provenance of the source text. Determines citation confidence and unblocks Phase 4 manuscript-witness graph work.
    """

    none_type_none = None
    manuscript = 'manuscript'
    manuscript_facsimile = 'manuscript_facsimile'
    critical_edition = 'critical_edition'
    scholarly_edition = 'scholarly_edition'
    paperback = 'paperback'
    hardcover = 'hardcover'
    publisher_pdf = 'publisher_pdf'
    scanned_pdf = 'scanned_pdf'
    web_html = 'web_html'
    born_digital = 'born_digital'
    audio_transcript = 'audio_transcript'
    video_transcript = 'video_transcript'
    unknown = 'unknown'


class Source(BaseModel):
    """
    Tenant corpus source document. Created by ingestion; chunks are produced from approved sources.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    source_id: str = Field(..., alias='sourceId')
    tenant_id: str = Field(..., alias='tenantId')
    title: constr(min_length=1)
    father: str | None = None
    work: str | None = None
    language: Language | None = 'en'
    source_type: SourceType = Field(..., alias='sourceType')
    source_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$') = Field(
        ...,
        alias='sourceHash',
        description='SHA-256 of raw bytes before processing, per decision register row J.',
    )
    extraction_method: str = Field(
        ...,
        alias='extractionMethod',
        description="Tool + version used for text extraction (e.g., 'pypdf@4.2.0').",
    )
    corpus_origin: (
        CorpusOrigin | constr(pattern=r'^monastery_archive:[a-z0-9_]+$') | None
    ) = Field(None, alias='corpusOrigin', description="Upstream corpus the source originated from. Drives Phase 3 cross-institution attribution and Phase 4 manuscript-partnership accounting. Use the catch-all 'tenant_upload' when no canonical upstream applies. The 'monastery_archive:<name>' prefix identifies a specific monastery archive (e.g., 'monastery_archive:simonopetra').")
    digitization_provenance: DigitizationProvenance | None = Field(
        None,
        alias='digitizationProvenance',
        description='Physical or digital provenance of the source text. Determines citation confidence and unblocks Phase 4 manuscript-witness graph work.',
    )
    approved: bool
    approval_note: str | None = Field(None, alias='approvalNote')
    approved_by: str | None = Field(None, alias='approvedBy')
    approved_at: AwareDatetime | None = Field(None, alias='approvedAt')
    corpus_version: str = Field(..., alias='corpusVersion')
    metadata: dict[str, Any] | None = Field(
        None,
        description='Free-form metadata: edition, translator, publisher, year, etc.',
    )
    created_at: AwareDatetime = Field(..., alias='createdAt')
