# generated by datamodel-codegen:
#   filename:  tenant.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr

from . import calendar_profile_schema


class Status(Enum):
    active = 'active'
    suspended = 'suspended'
    trial = 'trial'
    closed = 'closed'


class DataRegion(Enum):
    us = 'us'
    eu = 'eu'


class Tone(Enum):
    plain = 'plain'
    pastoral = 'pastoral'
    scholarly = 'scholarly'


class DefaultAnswerLength(Enum):
    short = 'short'
    medium = 'medium'
    long = 'long'


class SensitiveHandlingStrictness(Enum):
    standard = 'standard'
    strict = 'strict'


class EcclesiasticalJurisdiction(Enum):
    """
    Tenant ecclesiastical jurisdiction. Independent of calendarProfile (e.g., a GOARCH-jurisdiction tenant may run a revised-Julian fixed-feast calendar with a Julian Paschalion). Surfaces in citation context; drives the institutional_policy answer mode in Phase 2+. Phase 1: optional; recorded but not retrieval-influential. Use 'other' with ecclesiasticalJurisdictionOther for any value not in this enum.
    """

    none_type_none = None
    oca = 'oca'
    rocor = 'rocor'
    ecumenical_patriarchate = 'ecumenical_patriarchate'
    goarch = 'goarch'
    moscow_patriarchate = 'moscow_patriarchate'
    antiochian = 'antiochian'
    serbian = 'serbian'
    romanian = 'romanian'
    bulgarian = 'bulgarian'
    georgian = 'georgian'
    albanian = 'albanian'
    polish = 'polish'
    czech_slovak = 'czech_slovak'
    ukrainian_orthodox = 'ukrainian_orthodox'
    japanese = 'japanese'
    coptic = 'coptic'
    ethiopian = 'ethiopian'
    eritrean = 'eritrean'
    armenian = 'armenian'
    syriac = 'syriac'
    malankara = 'malankara'
    assyrian = 'assyrian'
    monastic_athonite = 'monastic_athonite'
    monastic_other = 'monastic_other'
    academic = 'academic'
    pan_orthodox = 'pan_orthodox'
    other = 'other'


class Config(BaseModel):
    """
    Safe tenant configuration mirror of /tenant/config. The calendarProfile is stored inline so the cache-key path tenants.config.calendarProfile.version (per docs/contracts/cache-key.md) is satisfied without a join.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    tone: Tone | None = None
    default_answer_length: DefaultAnswerLength | None = Field(
        None, alias='defaultAnswerLength'
    )
    citation_style: str | None = Field(None, alias='citationStyle')
    calendar_profile: calendar_profile_schema.CalendarProfile | None = Field(
        None, alias='calendarProfile'
    )
    starter_corpus_enabled: bool | None = Field(None, alias='starterCorpusEnabled')
    sensitive_handling_strictness: (
        SensitiveHandlingStrictness | None
    ) = Field(None, alias='sensitiveHandlingStrictness')
    disclaimer_template_id: str | None = Field(None, alias='disclaimerTemplateId')
    ecclesiastical_jurisdiction: (
        EcclesiasticalJurisdiction | None
    ) = (
        Field(None, alias='ecclesiasticalJurisdiction', description="Tenant ecclesiastical jurisdiction. Independent of calendarProfile (e.g., a GOARCH-jurisdiction tenant may run a revised-Julian fixed-feast calendar with a Julian Paschalion). Surfaces in citation context; drives the institutional_policy answer mode in Phase 2+. Phase 1: optional; recorded but not retrieval-influential. Use 'other' with ecclesiasticalJurisdictionOther for any value not in this enum.")
    )
    ecclesiastical_jurisdiction_other: (
        str | None
    ) = (
        Field(None, alias='ecclesiasticalJurisdictionOther', description="Free-text jurisdiction descriptor when ecclesiasticalJurisdiction == 'other'. Reviewer-facing; not parsed by retrieval or composition. Must be null when ecclesiasticalJurisdiction is any value other than 'other'.")
    )
    config_version: str | None = Field(None, alias='configVersion')
    corpus_version: str | None = Field(
        None,
        alias='corpusVersion',
        description='System-managed pointer to the active corpus version for this tenant. Set by the ingestion service on cutover; surfaces in cache-key recipe and on GET /tenant/config (read-only). Not editable via PATCH /tenant/config.',
    )


class Tenant(BaseModel):
    """
    Internal tenant record. Joined to Clerk org and Stripe customer.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    tenant_id: str = Field(..., alias='tenantId')
    name: constr(min_length=1)
    clerk_org_id: str = Field(..., alias='clerkOrgId')
    stripe_customer_id: str | None = Field(None, alias='stripeCustomerId')
    status: Status
    data_region: DataRegion = Field(..., alias='dataRegion')
    starter_corpus_enabled: bool | None = Field(False, alias='starterCorpusEnabled')
    config: Config | None = Field(
        None,
        description='Safe tenant configuration mirror of /tenant/config. The calendarProfile is stored inline so the cache-key path tenants.config.calendarProfile.version (per docs/contracts/cache-key.md) is satisfied without a join.',
    )
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime | None = Field(None, alias='updatedAt')
