# generated by datamodel-codegen:
#   filename:  user.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class Role(Enum):
    member = 'member'
    scholar = 'scholar'
    content_manager = 'content_manager'
    admin = 'admin'
    owner = 'owner'


class Status(Enum):
    active = 'active'
    invited = 'invited'
    disabled = 'disabled'


class User(BaseModel):
    """
    Internal user record. Source of truth for identity is Clerk; this row carries internal mapping and tenant binding.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    user_id: str = Field(..., alias='userId')
    clerk_user_id: str = Field(..., alias='clerkUserId')
    tenant_id: str = Field(..., alias='tenantId')
    email: EmailStr | None = None
    display_name: str | None = Field(None, alias='displayName')
    role: Role
    status: Status
    created_at: AwareDatetime = Field(..., alias='createdAt')
    last_seen_at: AwareDatetime | None = Field(None, alias='lastSeenAt')
