# generated by datamodel-codegen:
#   filename:  verified-response.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class ConfidenceTier(Enum):
    green = 'GREEN'
    yellow = 'YELLOW'
    red = 'RED'


class Handling(Enum):
    answer = 'answer'
    answer_with_disclaimer = 'answer_with_disclaimer'
    reframe_to_teaching = 'reframe_to_teaching'
    block_with_redirect = 'block_with_redirect'
    insufficient_evidence = 'insufficient_evidence'
    answer_1 = 'answer'
    answer_with_disclaimer_1 = 'answer_with_disclaimer'
    reframe_to_teaching_1 = 'reframe_to_teaching'


class CorpusOrigin(Enum):
    """
    Disclosure of the corpus the chunk came from. starter_corpus only appears when the tenant has the (Phase 2) feature enabled.
    """

    tenant = 'tenant'
    starter_corpus = 'starter_corpus'


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    citation_id: str = Field(..., alias='citationId')
    chunk_id: str = Field(..., alias='chunkId')
    source_id: str = Field(..., alias='sourceId')
    title: str
    work: str | None = None
    father: str | None = None
    page: str | None = None
    timestamp: str | None = None
    quote: str | None = None
    source_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$') = Field(
        ...,
        alias='sourceHash',
        description='Source-level integrity hash carried from EvidencePacket admittedChunks.sourceHash.',
    )
    chunk_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$') = Field(
        ...,
        alias='chunkHash',
        description='Chunk-level integrity hash carried from EvidencePacket admittedChunks.chunkHash.',
    )
    approved: Literal[True] = Field(
        ...,
        description='Always true. A6 admits only approved chunks; this is restated on the user-facing citation for downstream consumers and audit.',
    )
    corpus_origin: CorpusOrigin = Field(
        ...,
        alias='corpusOrigin',
        description='Disclosure of the corpus the chunk came from. starter_corpus only appears when the tenant has the (Phase 2) feature enabled.',
    )


class Verification(BaseModel):
    passed: bool
    checked_at: AwareDatetime = Field(..., alias='checkedAt')
    verifier_version: str = Field(..., alias='verifierVersion')
    failure_reason: str | None = Field(None, alias='failureReason')


class Reframing(BaseModel):
    was_reframed: bool = Field(..., alias='wasReframed')
    original_query: str | None = Field(None, alias='originalQuery')
    reframed_query: str | None = Field(None, alias='reframedQuery')
    disclosure_text: str | None = Field(None, alias='disclosureText')


class Usage(BaseModel):
    """
    Per-request accounting per ADR 0005. servedAnswerCount is always incremented (cache or fresh). freshModelRunCount only on cache miss.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    served_answer_count: conint(ge=0, le=1) = Field(..., alias='servedAnswerCount')
    fresh_model_run_count: conint(ge=0, le=1) = Field(..., alias='freshModelRunCount')
    model_route_id: str | None = Field(..., alias='modelRouteId')
    prompt_tokens: conint(ge=0) | None = Field(None, alias='promptTokens')
    completion_tokens: conint(ge=0) | None = Field(None, alias='completionTokens')


class ConfidenceTier2(Enum):
    """
    Confidence for this column alone, via the same A4 coverage rule applied to the column's chunks.
    """

    green = 'GREEN'
    yellow = 'YELLOW'
    red = 'RED'


class Position(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ...,
        description='Neutral label for the position, drawn from the evidence (father/work/council/era). Never model-invented.',
    )
    thesis: str = Field(
        ...,
        description="Short composed statement of this position, verified against this column's chunks only.",
    )
    citation_ids: list[str] = Field(
        ...,
        alias='citationIds',
        description='citationId values from the top-level citations[] belonging to THIS column only.',
    )
    confidence_tier: ConfidenceTier2 = Field(
        ...,
        alias='confidenceTier',
        description="Confidence for this column alone, via the same A4 coverage rule applied to the column's chunks.",
    )


class VerifiedResponse1(BaseModel):
    """
    Successful response paths must carry a runId.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    answer: str
    confidence_tier: ConfidenceTier = Field(..., alias='confidenceTier')
    handling: Handling
    citations: list[Citation]
    verification: Verification
    reframing: Reframing
    usage: Usage = Field(
        ...,
        description='Per-request accounting per ADR 0005. servedAnswerCount is always incremented (cache or fresh). freshModelRunCount only on cache miss.',
    )
    run_id: str = Field(
        ...,
        alias='runId',
        description='ULID identifying the pipeline run. Always present. Even on hard-safety bypass, a runId is minted and a minimal run_traces row is persisted (see phase1-implementation-contract.md §Run-trace persistence is unconditional).',
    )
    served_from_cache: bool = Field(..., alias='servedFromCache')
    schema_version: str = Field(
        ...,
        alias='schemaVersion',
        description='Format YYYY-MM-DD.NN per docs/contracts/api-versioning.md.',
    )
    positions: list[Position] | None = Field(
        None,
        description="Present (non-null) only for scholarly_dispute answers (T-006 §Scholarly Dispute UX). Competing positions rendered side-by-side; each position's citationIds are scoped to that column and reference the top-level citations[] — citations are NEVER aggregated across columns. Add-only optional field (api-versioning.md §Add-only changes do not bump), so schemaVersion is unchanged.",
    )


class ConfidenceTier3(Enum):
    green = 'GREEN'
    yellow = 'YELLOW'
    red = 'RED'


class Handling2(Enum):
    answer = 'answer'
    answer_with_disclaimer = 'answer_with_disclaimer'
    reframe_to_teaching = 'reframe_to_teaching'
    block_with_redirect = 'block_with_redirect'
    insufficient_evidence = 'insufficient_evidence'
    block_with_redirect_1 = 'block_with_redirect'
    insufficient_evidence_1 = 'insufficient_evidence'


class Citation1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    citation_id: str = Field(..., alias='citationId')
    chunk_id: str = Field(..., alias='chunkId')
    source_id: str = Field(..., alias='sourceId')
    title: str
    work: str | None = None
    father: str | None = None
    page: str | None = None
    timestamp: str | None = None
    quote: str | None = None
    source_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$') = Field(
        ...,
        alias='sourceHash',
        description='Source-level integrity hash carried from EvidencePacket admittedChunks.sourceHash.',
    )
    chunk_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$') = Field(
        ...,
        alias='chunkHash',
        description='Chunk-level integrity hash carried from EvidencePacket admittedChunks.chunkHash.',
    )
    approved: Literal[True] = Field(
        ...,
        description='Always true. A6 admits only approved chunks; this is restated on the user-facing citation for downstream consumers and audit.',
    )
    corpus_origin: CorpusOrigin = Field(
        ...,
        alias='corpusOrigin',
        description='Disclosure of the corpus the chunk came from. starter_corpus only appears when the tenant has the (Phase 2) feature enabled.',
    )


class ConfidenceTier4(Enum):
    """
    Confidence for this column alone, via the same A4 coverage rule applied to the column's chunks.
    """

    green = 'GREEN'
    yellow = 'YELLOW'
    red = 'RED'


class Position1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ...,
        description='Neutral label for the position, drawn from the evidence (father/work/council/era). Never model-invented.',
    )
    thesis: str = Field(
        ...,
        description="Short composed statement of this position, verified against this column's chunks only.",
    )
    citation_ids: list[str] = Field(
        ...,
        alias='citationIds',
        description='citationId values from the top-level citations[] belonging to THIS column only.',
    )
    confidence_tier: ConfidenceTier4 = Field(
        ...,
        alias='confidenceTier',
        description="Confidence for this column alone, via the same A4 coverage rule applied to the column's chunks.",
    )


class VerifiedResponse2(BaseModel):
    """
    Always present. Even on hard-safety bypass, a runId is minted and a minimal run_traces row is persisted (see phase1-implementation-contract.md §Run-trace persistence is unconditional).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    answer: str
    confidence_tier: ConfidenceTier3 = Field(..., alias='confidenceTier')
    handling: Handling2
    citations: list[Citation1]
    verification: Verification
    reframing: Reframing
    usage: Usage = Field(
        ...,
        description='Per-request accounting per ADR 0005. servedAnswerCount is always incremented (cache or fresh). freshModelRunCount only on cache miss.',
    )
    run_id: str = Field(
        ...,
        alias='runId',
        description='ULID identifying the pipeline run. Always present. Even on hard-safety bypass, a runId is minted and a minimal run_traces row is persisted (see phase1-implementation-contract.md §Run-trace persistence is unconditional).',
    )
    served_from_cache: bool = Field(..., alias='servedFromCache')
    schema_version: str = Field(
        ...,
        alias='schemaVersion',
        description='Format YYYY-MM-DD.NN per docs/contracts/api-versioning.md.',
    )
    positions: list[Position1] | None = Field(
        None,
        description="Present (non-null) only for scholarly_dispute answers (T-006 §Scholarly Dispute UX). Competing positions rendered side-by-side; each position's citationIds are scoped to that column and reference the top-level citations[] — citations are NEVER aggregated across columns. Add-only optional field (api-versioning.md §Add-only changes do not bump), so schemaVersion is unchanged.",
    )


class VerifiedResponse(RootModel[VerifiedResponse1 | VerifiedResponse2]):
    root: VerifiedResponse1 | VerifiedResponse2 = Field(..., title='VerifiedResponse')
