/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkflowsRouteImport } from './routes/_app.workflows'
import { Route as AppWidgetRouteImport } from './routes/_app.widget'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppTeachMeRouteImport } from './routes/_app.teach-me'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSafetyRouteImport } from './routes/_app.safety'
import { Route as AppResearchRouteImport } from './routes/_app.research'
import { Route as AppPromptLabRouteImport } from './routes/_app.prompt-lab'
import { Route as AppOfflineRouteImport } from './routes/_app.offline'
import { Route as AppModelRoutesRouteImport } from './routes/_app.model-routes'
import { Route as AppLineageRouteImport } from './routes/_app.lineage'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppGovernanceRouteImport } from './routes/_app.governance'
import { Route as AppGapsRouteImport } from './routes/_app.gaps'
import { Route as AppCorpusRouteImport } from './routes/_app.corpus'
import { Route as AppCitationsRouteImport } from './routes/_app.citations'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAttestationsRouteImport } from './routes/_app.attestations'
import { Route as AppAssistantRouteImport } from './routes/_app.assistant'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppWidgetRoute = AppWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachMeRoute = AppTeachMeRouteImport.update({
  id: '/teach-me',
  path: '/teach-me',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyRoute = AppSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptLabRoute = AppPromptLabRouteImport.update({
  id: '/prompt-lab',
  path: '/prompt-lab',
  getParentRoute: () => AppRoute,
} as any)
const AppOfflineRoute = AppOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => AppRoute,
} as any)
const AppModelRoutesRoute = AppModelRoutesRouteImport.update({
  id: '/model-routes',
  path: '/model-routes',
  getParentRoute: () => AppRoute,
} as any)
const AppLineageRoute = AppLineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppGovernanceRoute = AppGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AppRoute,
} as any)
const AppGapsRoute = AppGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => AppRoute,
} as any)
const AppCorpusRoute = AppCorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => AppRoute,
} as any)
const AppCitationsRoute = AppCitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAttestationsRoute = AppAttestationsRouteImport.update({
  id: '/attestations',
  path: '/attestations',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assistant': typeof AppAssistantRoute
  '/attestations': typeof AppAttestationsRoute
  '/billing': typeof AppBillingRoute
  '/citations': typeof AppCitationsRoute
  '/corpus': typeof AppCorpusRoute
  '/gaps': typeof AppGapsRoute
  '/governance': typeof AppGovernanceRoute
  '/history': typeof AppHistoryRoute
  '/lineage': typeof AppLineageRoute
  '/model-routes': typeof AppModelRoutesRoute
  '/offline': typeof AppOfflineRoute
  '/prompt-lab': typeof AppPromptLabRoute
  '/research': typeof AppResearchRoute
  '/safety': typeof AppSafetyRoute
  '/settings': typeof AppSettingsRoute
  '/teach-me': typeof AppTeachMeRoute
  '/team': typeof AppTeamRoute
  '/widget': typeof AppWidgetRoute
  '/workflows': typeof AppWorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assistant': typeof AppAssistantRoute
  '/attestations': typeof AppAttestationsRoute
  '/billing': typeof AppBillingRoute
  '/citations': typeof AppCitationsRoute
  '/corpus': typeof AppCorpusRoute
  '/gaps': typeof AppGapsRoute
  '/governance': typeof AppGovernanceRoute
  '/history': typeof AppHistoryRoute
  '/lineage': typeof AppLineageRoute
  '/model-routes': typeof AppModelRoutesRoute
  '/offline': typeof AppOfflineRoute
  '/prompt-lab': typeof AppPromptLabRoute
  '/research': typeof AppResearchRoute
  '/safety': typeof AppSafetyRoute
  '/settings': typeof AppSettingsRoute
  '/teach-me': typeof AppTeachMeRoute
  '/team': typeof AppTeamRoute
  '/widget': typeof AppWidgetRoute
  '/workflows': typeof AppWorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/attestations': typeof AppAttestationsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/citations': typeof AppCitationsRoute
  '/_app/corpus': typeof AppCorpusRoute
  '/_app/gaps': typeof AppGapsRoute
  '/_app/governance': typeof AppGovernanceRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/lineage': typeof AppLineageRoute
  '/_app/model-routes': typeof AppModelRoutesRoute
  '/_app/offline': typeof AppOfflineRoute
  '/_app/prompt-lab': typeof AppPromptLabRoute
  '/_app/research': typeof AppResearchRoute
  '/_app/safety': typeof AppSafetyRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/teach-me': typeof AppTeachMeRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/widget': typeof AppWidgetRoute
  '/_app/workflows': typeof AppWorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/attestations'
    | '/billing'
    | '/citations'
    | '/corpus'
    | '/gaps'
    | '/governance'
    | '/history'
    | '/lineage'
    | '/model-routes'
    | '/offline'
    | '/prompt-lab'
    | '/research'
    | '/safety'
    | '/settings'
    | '/teach-me'
    | '/team'
    | '/widget'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/attestations'
    | '/billing'
    | '/citations'
    | '/corpus'
    | '/gaps'
    | '/governance'
    | '/history'
    | '/lineage'
    | '/model-routes'
    | '/offline'
    | '/prompt-lab'
    | '/research'
    | '/safety'
    | '/settings'
    | '/teach-me'
    | '/team'
    | '/widget'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/analytics'
    | '/_app/assistant'
    | '/_app/attestations'
    | '/_app/billing'
    | '/_app/citations'
    | '/_app/corpus'
    | '/_app/gaps'
    | '/_app/governance'
    | '/_app/history'
    | '/_app/lineage'
    | '/_app/model-routes'
    | '/_app/offline'
    | '/_app/prompt-lab'
    | '/_app/research'
    | '/_app/safety'
    | '/_app/settings'
    | '/_app/teach-me'
    | '/_app/team'
    | '/_app/widget'
    | '/_app/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/widget': {
      id: '/_app/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof AppWidgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teach-me': {
      id: '/_app/teach-me'
      path: '/teach-me'
      fullPath: '/teach-me'
      preLoaderRoute: typeof AppTeachMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/safety': {
      id: '/_app/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof AppSafetyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/research': {
      id: '/_app/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prompt-lab': {
      id: '/_app/prompt-lab'
      path: '/prompt-lab'
      fullPath: '/prompt-lab'
      preLoaderRoute: typeof AppPromptLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offline': {
      id: '/_app/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof AppOfflineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/model-routes': {
      id: '/_app/model-routes'
      path: '/model-routes'
      fullPath: '/model-routes'
      preLoaderRoute: typeof AppModelRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lineage': {
      id: '/_app/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof AppLineageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/governance': {
      id: '/_app/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AppGovernanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gaps': {
      id: '/_app/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof AppGapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/corpus': {
      id: '/_app/corpus'
      path: '/corpus'
      fullPath: '/corpus'
      preLoaderRoute: typeof AppCorpusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/citations': {
      id: '/_app/citations'
      path: '/citations'
      fullPath: '/citations'
      preLoaderRoute: typeof AppCitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attestations': {
      id: '/_app/attestations'
      path: '/attestations'
      fullPath: '/attestations'
      preLoaderRoute: typeof AppAttestationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppAttestationsRoute: typeof AppAttestationsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCitationsRoute: typeof AppCitationsRoute
  AppCorpusRoute: typeof AppCorpusRoute
  AppGapsRoute: typeof AppGapsRoute
  AppGovernanceRoute: typeof AppGovernanceRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLineageRoute: typeof AppLineageRoute
  AppModelRoutesRoute: typeof AppModelRoutesRoute
  AppOfflineRoute: typeof AppOfflineRoute
  AppPromptLabRoute: typeof AppPromptLabRoute
  AppResearchRoute: typeof AppResearchRoute
  AppSafetyRoute: typeof AppSafetyRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeachMeRoute: typeof AppTeachMeRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWidgetRoute: typeof AppWidgetRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppAttestationsRoute: AppAttestationsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCitationsRoute: AppCitationsRoute,
  AppCorpusRoute: AppCorpusRoute,
  AppGapsRoute: AppGapsRoute,
  AppGovernanceRoute: AppGovernanceRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLineageRoute: AppLineageRoute,
  AppModelRoutesRoute: AppModelRoutesRoute,
  AppOfflineRoute: AppOfflineRoute,
  AppPromptLabRoute: AppPromptLabRoute,
  AppResearchRoute: AppResearchRoute,
  AppSafetyRoute: AppSafetyRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeachMeRoute: AppTeachMeRoute,
  AppTeamRoute: AppTeamRoute,
  AppWidgetRoute: AppWidgetRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
